services:
    web-server:
        build: .
        container_name: php
        depends_on:
            - db-server
        volumes:
            - ./www:/var/www/html/
        ports:
            - 5050:80

    db-server:
        image: mariadb
        restart: always
        container_name: db
        volumes:
            - mariadb-data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d/
        environment:
            MARIADB_DATABASE: eman
            MARIADB_ROOT_PASSWORD: abc
        ports:
          - 6060:3306
volumes:
  mariadb-data: